import {memoryFetch,startMemoryClient} from './memory-client.js';
import * as THREE from 'three';
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';
import {MeshoptDecoder} from 'three/examples/jsm/libs/meshopt_decoder.module.js';
import {geoEquirectangular,geoPath} from 'd3-geo';
import {feature} from 'topojson-client';
// 依赖全部打进 app.bundle.js（见 build.mjs），不走 jsdelivr：国内网络下 CDN 不稳，现场不能赌
import worldAtlas from 'world-atlas/countries-110m.json';

const coarsePointer=matchMedia('(pointer: coarse)').matches;
// 手机粒子预算降到 6 万（桌面保持 18 万）；fit/far0/far1/pointScale 按屏幕比例在 resize 里算
const C={budget:coarsePointer?60000:180000,batch:20,camRadius:.08,cameraCollisionScale:.56,fit:7.2,far0:7,far1:12,pointScale:1};
const params=new URLSearchParams(location.search),embedded=window.parent!==window&&params.get('source')==='parent';
if(embedded)document.documentElement.classList.add('embedded');
const $=s=>document.querySelector(s),root=$('#scene'),ui={loading:$('#loading'),back:$('#return-line')};
const scene=new THREE.Scene();scene.background=new THREE.Color('#292c3d');scene.fog=new THREE.FogExp2('#292c3d',.032);
const camera=new THREE.PerspectiveCamera(52,1,.04,80);camera.position.set(0,0,7.2);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.outputColorSpace=THREE.SRGBColorSpace;root.appendChild(renderer.domElement);
const world=new THREE.Group();scene.add(world);const loader=new GLTFLoader();loader.setMeshoptDecoder(MeshoptDecoder);
function seededRandom(seed){const x=Math.sin(seed*12.9898+78.233)*43758.5453;return x-Math.floor(x)}
function createMemoryStars(){const count=2200,positions=new Float32Array(count*3),colors=new Float32Array(count*3);for(let i=0;i<count;i++){const u=seededRandom(i+1),v=seededRandom(i+91),w=seededRandom(i+313),radius=11+25*Math.pow(w,.72),theta=u*Math.PI*2,band=seededRandom(i+701)<.38,y=band?(v-.5)*radius*.3:(v*2-1)*radius,ring=Math.sqrt(Math.max(0,radius*radius-y*y));positions[i*3]=Math.cos(theta)*ring;positions[i*3+1]=y;positions[i*3+2]=Math.sin(theta)*ring;const tone=.76+seededRandom(i+997)*.24;colors[i*3]=tone*.92;colors[i*3+1]=tone*.96;colors[i*3+2]=tone}const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(positions,3));geometry.setAttribute('color',new THREE.BufferAttribute(colors,3));const material=new THREE.PointsMaterial({size:1.35,sizeAttenuation:false,vertexColors:true,transparent:true,opacity:.34,depthWrite:false,fog:false,blending:THREE.NormalBlending});const stars=new THREE.Points(geometry,material);stars.name='memory-stars';scene.add(stars);return stars}
const memoryStars=createMemoryStars();
function createAxisGlobe(){
  const canvas=document.createElement('canvas');canvas.width=1024;canvas.height=512;const ctx=canvas.getContext('2d'),texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;texture.wrapS=THREE.RepeatWrapping;
  const paintBase=()=>{ctx.fillStyle='#020912';ctx.fillRect(0,0,canvas.width,canvas.height)};paintBase();
  Promise.resolve(worldAtlas).then(topology=>{paintBase();const countries=feature(topology,topology.objects.countries),projection=geoEquirectangular().translate([canvas.width/2,canvas.height/2]).scale(canvas.width/(2*Math.PI)),path=geoPath(projection,ctx);ctx.beginPath();path(countries);ctx.fillStyle='#ff0000';ctx.fill();ctx.lineWidth=1.2;ctx.strokeStyle='#0000ff';ctx.globalAlpha=1;ctx.stroke();texture.needsUpdate=true}).catch(error=>console.warn('地球地图纹路载入失败',error));
  const globeMaterial=new THREE.ShaderMaterial({transparent:true,depthWrite:false,uniforms:{mapTexture:{value:texture},lineColor:{value:new THREE.Color('#ffffff')},backgroundColor:{value:new THREE.Color('#3f6092')}},vertexShader:`varying vec2 vUv;varying vec3 vNormal;varying vec3 vView;void main(){vUv=uv;vec4 mv=modelViewMatrix*vec4(position,1.);vNormal=normalize(normalMatrix*normal);vView=normalize(-mv.xyz);gl_Position=projectionMatrix*mv;}`,fragmentShader:`uniform sampler2D mapTexture;uniform vec3 lineColor;uniform vec3 backgroundColor;varying vec2 vUv;varying vec3 vNormal;varying vec3 vView;void main(){vec3 mask=texture2D(mapTexture,vUv).rgb;float land=smoothstep(.2,.8,mask.r);float ocean=1.-land;float line=mask.b;float rim=pow(1.-max(dot(normalize(vNormal),normalize(vView)),0.),12.);float detail=clamp(line+rim*.82,0.,1.);float baseAlpha=.5*ocean;float alpha=detail+baseAlpha*(1.-detail);vec3 premultiplied=lineColor*detail+backgroundColor*baseAlpha*(1.-detail);vec3 color=alpha>.001?premultiplied/alpha:lineColor;gl_FragColor=vec4(color,alpha);}`});
  const group=new THREE.Group(),sphere=new THREE.Mesh(new THREE.SphereGeometry(.22,48,32),globeMaterial);group.add(sphere);
  scene.add(group);return{group,sphere,material:globeMaterial}
}
const axisGlobe=createAxisGlobe();
function createMemoryAtmosphere(){const canvas=document.createElement('canvas');canvas.width=1024;canvas.height=512;const ctx=canvas.getContext('2d'),texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;texture.mapping=THREE.UVMapping;texture.minFilter=THREE.LinearFilter;texture.magFilter=THREE.LinearFilter;scene.background=texture;return{canvas,ctx,texture,refreshToken:0,paintedToken:-1,lastColor:''}}
const memoryAtmosphere=createMemoryAtmosphere();
const models=[],keys=new Set(),clock=new THREE.Clock();let userMoved=false,focusedId=null,pendingFocus=null,yaw=0,pitch=0,drag=false,lastX=0,lastY=0,pointerDownX=0,pointerDownY=0,lastInput=performance.now(),line,layoutPositions=[],lastBudgetUpdate=0,budgetTargets=new Map();
const vs=`attribute vec3 particleColor;uniform float time,spread,size,highlight;varying vec3 vColor;float h(vec3 q){return fract(sin(dot(q,vec3(12.9898,78.233,37.719)))*43758.5453);}void main(){vec3 n=normalize(vec3(h(position),h(position.yzx+2.1),h(position.zxy+4.2))-.5+normalize(position+.001)*.28);float phase=time*(.35+h(position)*.9)+dot(position,vec3(17.,19.,23.));float pulse=.55+.45*sin(phase);vec3 brown=vec3(sin(phase*1.7),sin(phase*1.31+2.1),sin(phase*1.13+4.2))*.018;vec3 p=position+(n*pulse+brown)*spread*.12;vec4 mv=modelViewMatrix*vec4(p,1.);gl_Position=projectionMatrix*mv;gl_PointSize=min(10.,size*(1.+highlight*.1)/max(.8,-mv.z));vColor=particleColor;}`;
const fs=`precision mediump float;varying vec3 vColor;uniform float alpha;void main(){float d=length(gl_PointCoord-.5);if(d>.5)discard;float edge=1.-smoothstep(.34,.5,d);gl_FragColor=vec4(vColor,alpha*edge);}`;


function boostColor(color,amount=1.35){const hsl={h:0,s:0,l:0};color.getHSL(hsl);return color.clone().setHSL(hsl.h,Math.min(1,hsl.s*amount+.06),THREE.MathUtils.clamp(hsl.l*1.03,.06,.94))}
function paletteFromImage(image){try{const cv=document.createElement('canvas'),x=cv.getContext('2d',{willReadFrequently:true});cv.width=cv.height=72;x.drawImage(image,0,0,72,72);const d=x.getImageData(0,0,72,72).data,samples=[];for(let i=0;i<d.length;i+=16){const r=d[i]/255,g=d[i+1]/255,b=d[i+2]/255,light=(r+g+b)/3;if(d[i+3]<80||light<.015||light>.985)continue;samples.push([r,g,b])}if(samples.length<3)return[];samples.sort((a,b)=>(a[0]+a[1]+a[2])-(b[0]+b[1]+b[2]));let centers=[samples[Math.floor(samples.length*.12)].slice(),samples[Math.floor(samples.length*.5)].slice(),samples[Math.floor(samples.length*.88)].slice()];for(let pass=0;pass<10;pass++){const sums=[[0,0,0,0],[0,0,0,0],[0,0,0,0]];for(const p of samples){let best=0,dist=Infinity;for(let k=0;k<3;k++){const c=centers[k],v=(p[0]-c[0])**2+(p[1]-c[1])**2+(p[2]-c[2])**2;if(v<dist){dist=v;best=k}}sums[best][0]+=p[0];sums[best][1]+=p[1];sums[best][2]+=p[2];sums[best][3]++}centers=centers.map((c,k)=>sums[k][3]?[sums[k][0]/sums[k][3],sums[k][1]/sums[k][3],sums[k][2]/sums[k][3]]:c)}return centers.map(c=>boostColor(new THREE.Color(c[0],c[1],c[2])))}catch{return[]}}
async function embeddedPalette(buffer){try{const v=new DataView(buffer);let offset=12,json,binOffset=0;while(offset<buffer.byteLength){const length=v.getUint32(offset,true),type=v.getUint32(offset+4,true);offset+=8;if(type===0x4e4f534a)json=JSON.parse(new TextDecoder().decode(new Uint8Array(buffer,offset,length)).replace(/\0+$/,''));if(type===0x004e4942)binOffset=offset;offset+=length}const image=json?.images?.find(i=>i.bufferView!==undefined);if(!image)return[];const view=json.bufferViews[image.bufferView],start=binOffset+(view.byteOffset||0),blob=new Blob([buffer.slice(start,start+view.byteLength)],{type:image.mimeType||'image/jpeg'}),bitmap=await createImageBitmap(blob),palette=paletteFromImage(bitmap);bitmap.close();return palette}catch(e){console.warn('主色提取回退',e);return[]}}
async function load(url){const response=url.startsWith('./models-source/')||url.startsWith('/')||url.startsWith('blob:')?await fetch(url):await memoryFetch(url);if(!response.ok)throw Error(`HTTP ${response.status}`);const buffer=await response.arrayBuffer(),palettePromise=embeddedPalette(buffer),gltf=await new Promise((ok,no)=>loader.parse(buffer,'',ok,no));return{gltf,palette:await palettePromise}}
function mainPalette(mat){const base=mat?.color?.clone?.()||new THREE.Color(.7,.84,.76),fallback=[base.clone(),base.clone().multiplyScalar(.7),base.clone().lerp(new THREE.Color(1,1,1),.25)],im=mat?.map?.image;if(!im?.width)return fallback;try{const cv=document.createElement('canvas'),x=cv.getContext('2d',{willReadFrequently:true});cv.width=cv.height=48;x.drawImage(im,0,0,48,48);const d=x.getImageData(0,0,48,48).data,bins=new Map();for(let i=0;i<d.length;i+=16){const light=(d[i]+d[i+1]+d[i+2])/3;if(light<14||light>248||d[i+3]<80)continue;const key=((d[i]>>4)<<8)|((d[i+1]>>4)<<4)|(d[i+2]>>4);bins.set(key,(bins.get(key)||0)+1)}const out=[];for(const[key]of[...bins].sort((a,b)=>b[1]-a[1])){const c=new THREE.Color(((key>>8)&15)/15,((key>>4)&15)/15,(key&15)/15);if(out.every(q=>q.distanceTo(c)>.18))out.push(c);if(out.length===3)break}return out.length?Array.from({length:3},(_,i)=>out[i]||out[0]):fallback}catch{return fallback}}
function prepare(gltf,name,index,modelPalette){
  gltf.scene.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(gltf.scene),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3()),scale=1.65/Math.max(size.x,size.y,size.z,.001),pos=[],colors=[];
  gltf.scene.traverse(o=>{if(!o.isMesh||!o.geometry?.attributes?.position)return;const a=o.geometry.attributes.position,fallback=mainPalette(Array.isArray(o.material)?o.material[0]:o.material),palette=modelPalette?.length?modelPalette:fallback,step=Math.max(1,Math.floor(a.count/24000)),v=new THREE.Vector3();for(let i=0;i<a.count;i+=step){v.fromBufferAttribute(a,i).applyMatrix4(o.matrixWorld).sub(center).multiplyScalar(scale);pos.push(v.x,v.y,v.z);const col=palette[Math.abs(Math.floor(v.x*17+v.y*29+v.z*37+i))%palette.length];colors.push(col.r,col.g,col.b)}});
  gltf.scene.position.copy(center).multiplyScalar(-scale);gltf.scene.scale.setScalar(scale);gltf.scene.traverse(o=>{if(o.isMesh){const one=m=>{const dominant=boostColor(modelPalette?.[0]||mainPalette(m)[0],1.18),q=new THREE.MeshBasicMaterial({map:m?.map||null,alphaMap:m?.alphaMap||null,color:m?.map?0xffffff:dominant,vertexColors:Boolean(m?.vertexColors),transparent:true,opacity:.2,depthWrite:false,side:m?.side??THREE.FrontSide,alphaTest:m?.alphaTest||0});q.onBeforeCompile=shader=>{shader.fragmentShader=shader.fragmentShader.replace('#include <map_fragment>','#include <map_fragment>\nfloat memoryLuma=dot(diffuseColor.rgb,vec3(.299,.587,.114));diffuseColor.rgb=mix(vec3(memoryLuma),diffuseColor.rgb,1.22);')};return q};o.material=Array.isArray(o.material)?o.material.map(one):one(o.material)}});
  const group=new THREE.Group(),keepVisual=index<C.batch;if(keepVisual)group.add(gltf.scene);else gltf.scene.traverse(o=>{if(o.isMesh){o.geometry?.dispose();const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>{m?.map?.dispose();m?.dispose()})}});const saved=layoutPositions[index]||[0,0,0,0,0,0];group.position.fromArray(saved);group.rotation.set(saved[3]||0,saved[4]||0,saved[5]||0);world.add(group);
  return{name,index,group,visual:keepVisual?gltf.scene:null,palette:modelPalette?.length?modelPalette:mainPalette(null),source:new Float32Array(pos),colors:new Float32Array(colors),radius:Math.max(.3,new THREE.Vector3(size.x*scale,size.y*scale,size.z*scale).length()*.31),born:true,frozen:true,points:null};
}
function radicalInverse(n){let x=0,f=.5;while(n>0){x+=(n&1)*f;n>>=1;f*=.5}return x}
function particles(){const nearShare=Math.floor(C.budget*.2);for(const m of models){if(!m||m.points)continue;const available=m.source.length/3,count=Math.min(nearShare,available),p=new Float32Array(count*3),c=new Float32Array(count*3),offset=(m.index*.137503)%1;for(let i=0;i<count;i++){const progressive=(radicalInverse(i+1)+offset)%1,n=Math.min(available-1,Math.floor(progressive*available))*3;p.set(m.source.subarray(n,n+3),i*3);c.set(m.colors.subarray(n,n+3),i*3)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(p,3));g.setAttribute('particleColor',new THREE.BufferAttribute(c,3));const mat=new THREE.ShaderMaterial({vertexShader:vs,fragmentShader:fs,transparent:true,depthWrite:false,uniforms:{time:{value:0},spread:{value:1},size:{value:14},alpha:{value:.72},highlight:{value:0}}});m.points=new THREE.Points(g,mat);m.group.add(m.points)}}
function getStableLayout(files){const signature=files.map(f=>f.id).join('|'),key=`memoryUniverseLayout:v5:${signature}`,saved=localStorage.getItem(key);if(saved)try{return JSON.parse(saved)}catch{}const n=files.length,out=[],core=Math.min(5,n),coreRadius=.92,corePoints=[[0,1,0],[0,-1,0],[1,0,0],[-.5,0,.866],[-.5,0,-.866]];for(let i=0;i<core;i++){const v=new THREE.Vector3(...corePoints[i]).multiplyScalar(coreRadius);out.push([v.x,v.y,v.z,(i%3)*.18,(i*1.31)%6.28,(i%2)*.14])}let index=core,shell=0;while(index<n){const frequency=shell+1,capacity=10*frequency*frequency+2,radius=2.45+shell*1.55,count=Math.min(capacity,n-index);for(let slot=0;slot<count;slot++,index++){const y=1-2*(slot+.5)/capacity,r=Math.sqrt(Math.max(0,1-y*y)),a=(slot+shell*.37)*2.399963,depth=radius+(seededRandom(index+5101)-.5)*.2;out.push([Math.cos(a)*r*depth,y*depth,Math.sin(a)*r*depth,(index%5)*.13,(index*1.17)%6.28,(index%7)*.09])}shell++}localStorage.setItem(key,JSON.stringify(out));return out}

function buildLine(){if(line){scene.remove(line);line.geometry.dispose();line.material.dispose();}const ready=models.filter(Boolean);if(ready.length<2)return;const curve=new THREE.CatmullRomCurve3(ready.map(m=>m.group.position.clone()),true,'centripetal',.25),g=new THREE.BufferGeometry().setFromPoints(curve.getPoints(Math.min(900,ready.length*12)));line=new THREE.LineLoop(g,new THREE.LineBasicMaterial({color:'#8fd8ff',transparent:true,opacity:.13,depthWrite:false}));scene.add(line)}
function nearest(){let best,dist=Infinity;for(const m of models){if(!m?.born)continue;const d=camera.position.distanceTo(m.group.position);if(d<dist){best=m;dist=d}}return[best,dist]}
function aggregateCenter(){return new THREE.Vector3()}
function aimAt(target){const direction=target.clone().sub(camera.position).normalize();pitch=Math.asin(THREE.MathUtils.clamp(direction.y,-1,1));yaw=Math.atan2(-direction.x,-direction.z)}
// 聚焦某件记忆时，自动环绕改为绕它转，镜头始终对着它；碰屏幕后恢复绕中心
function orbitTarget(){const m=focusedId&&models.find(x=>x?.id===focusedId);return m?m.group.position.clone():aggregateCenter()}
function orbitAroundCenter(dx,dy,automatic=false){const target=orbitTarget(),before=camera.position.clone(),offset=before.clone().sub(target),spherical=new THREE.Spherical().setFromVector3(offset);spherical.theta-=dx*.004;spherical.phi=THREE.MathUtils.clamp(spherical.phi-dy*.004,.08,Math.PI-.08);let desired=target.clone().add(new THREE.Vector3().setFromSpherical(spherical)),resolved=collide(desired,before);if(automatic&&resolved.distanceToSquared(before)<desired.distanceToSquared(before)*.08){spherical.radius+=Math.max(.035,spherical.radius*.004);desired=target.clone().add(new THREE.Vector3().setFromSpherical(spherical));resolved=collide(desired,before,true)}camera.position.copy(resolved);aimAt(target)}
function collide(next,current=null,allowBypass=false){for(let pass=0;pass<3;pass++){let hit=null,deepest=0;for(const m of models){if(!m?.frozen)continue;const min=m.radius*C.cameraCollisionScale+C.camRadius,d=next.distanceTo(m.group.position),depth=min-d;if(depth>deepest){deepest=depth;hit={m,min}}}if(!hit)break;const d=next.clone().sub(hit.m.group.position),len=d.length();let normal=len>.0001?d.multiplyScalar(1/len):(current?current.clone().sub(hit.m.group.position).normalize():new THREE.Vector3(0,1,0));if(allowBypass&&current){const travel=next.clone().sub(current),tangent=travel.addScaledVector(normal,-travel.dot(normal));if(tangent.lengthSq()<1e-6)tangent.crossVectors(normal,Math.abs(normal.y)<.9?new THREE.Vector3(0,1,0):new THREE.Vector3(1,0,0)).setLength(.012);next.copy(current).add(tangent);const adjusted=next.clone().sub(hit.m.group.position);normal=adjusted.lengthSq()>.000001?adjusted.normalize():normal}next.copy(hit.m.group.position).add(normal.multiplyScalar(hit.min+.002))}return next}
function move(dt,now){const f=new THREE.Vector3(-Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),-Math.cos(yaw)*Math.cos(pitch)),r=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw)),d=new THREE.Vector3(),s=1.75*dt;if(keys.has('w'))d.addScaledVector(f,s);if(keys.has('s'))d.addScaledVector(f,-s);if(keys.has('a'))d.addScaledVector(r,-s);if(keys.has('d'))d.addScaledVector(r,s);if(keys.has('q'))d.y-=s;if(keys.has('e'))d.y+=s;if(d.lengthSq())lastInput=now;camera.position.copy(collide(camera.position.clone().add(d),camera.position,d.lengthSq()>0));const[m,dist]=nearest(),idle=(now-lastInput)/1000,isMoving=d.lengthSq()>0,userStillNavigating=now-lastInput<220;if(models.length&&!drag&&!isMoving&&!userStillNavigating)orbitAroundCenter(-9*dt,0,true);if(m)ui.back.hidden=embedded||(idle<12&&dist<4.5);camera.rotation.order='YXZ';camera.rotation.y=yaw;camera.rotation.x=pitch}
function diffusionAtSurfaceDistance(d){if(d<1.8)return 1+2*THREE.MathUtils.smoothstep(1.8-d,0,1.8);if(d<C.far0)return 1;return 1+2*THREE.MathUtils.smoothstep(d,C.far0,C.far1)}
function colorCss(color,alpha=1){return`rgba(${Math.round(color.r*255)},${Math.round(color.g*255)},${Math.round(color.b*255)},${alpha})`}
function dominantTendency(palettes){if(!palettes.length)return new THREE.Color(.22,.27,.38);const bins=Array(12).fill(0),values=palettes.map(color=>{const hsl={h:0,s:0,l:0};color.getHSL(hsl);const weight=.25+hsl.s*.75;bins[Math.floor(hsl.h*12)%12]+=weight;return{...hsl,weight}}),scores=bins.map((v,i)=>v+bins[(i+11)%12]*.45+bins[(i+1)%12]*.45),dominant=scores.indexOf(Math.max(...scores));let sin=0,cos=0,s=0,l=0,total=0;for(const value of values){const bin=Math.floor(value.h*12)%12,distance=Math.min((bin-dominant+12)%12,(dominant-bin+12)%12);if(distance>1)continue;sin+=Math.sin(value.h*Math.PI*2)*value.weight;cos+=Math.cos(value.h*Math.PI*2)*value.weight;s+=value.s*value.weight;l+=value.l*value.weight;total+=value.weight}if(!total){total=1}const modelHue=(Math.atan2(sin,cos)/(Math.PI*2)+1)%1,complementHue=(modelHue+.5)%1,baseSaturation=THREE.MathUtils.clamp(Math.max(.58,s/total),.58,.76),baseLightness=THREE.MathUtils.clamp(Math.max(.44,l/total),.44,.58),saturation=Math.min(.95,baseSaturation*1.25),lightness=baseLightness*.4096;return new THREE.Color().setHSL(complementHue,saturation,lightness)}
function updateMemoryAtmosphere(){if(memoryAtmosphere.paintedToken===memoryAtmosphere.refreshToken)return;memoryAtmosphere.paintedToken=memoryAtmosphere.refreshToken;const ready=models.filter(m=>m?.palette?.length),{canvas,ctx,texture}=memoryAtmosphere,palettes=ready.flatMap(m=>m.palette),tendency=dominantTendency(palettes);ctx.fillStyle=colorCss(tendency);ctx.fillRect(0,0,canvas.width,canvas.height);const sources=ready.length?ready:[{index:0,palette:[tendency]}];for(const m of sources){const ax=seededRandom(m.index+2101)*canvas.width,ay=(.16+seededRandom(m.index+2301)*.68)*canvas.height;for(let k=0;k<m.palette.length;k++){const hsl={h:0,s:0,l:0};m.palette[k].getHSL(hsl);const color=new THREE.Color().setHSL(hsl.h,hsl.s,hsl.l*.64),ox=(seededRandom(m.index*17+k+2501)-.5)*260,oy=(seededRandom(m.index*19+k+2701)-.5)*150,radius=220+seededRandom(m.index*23+k+2901)*300,g=ctx.createRadialGradient(ax+ox,ay+oy,0,ax+ox,ay+oy,radius);g.addColorStop(0,colorCss(color,.08));g.addColorStop(.48,colorCss(color,.03));g.addColorStop(1,colorCss(color,0));ctx.fillStyle=g;ctx.fillRect(0,0,canvas.width,canvas.height)}}memoryAtmosphere.lastColor=`#${tendency.getHexString()}`;texture.needsUpdate=true;scene.background=texture;console.info('记忆背景补色',memoryAtmosphere.lastColor,'来源模型',ready.length)}
function distributeBudget(active,near){const minimum=300,allocation=new Map();let remaining=C.budget;for(const m of active){const cap=m.points.geometry.attributes.position.count,give=Math.min(minimum,cap);allocation.set(m,give);remaining-=give}if(near&&allocation.has(near)){const cap=near.points.geometry.attributes.position.count,target=Math.min(cap,Math.floor(C.budget*.2)),extra=Math.min(remaining,Math.max(0,target-allocation.get(near)));allocation.set(near,allocation.get(near)+extra);remaining-=extra}let waiting=active.filter(m=>m!==near&&allocation.get(m)<m.points.geometry.attributes.position.count);for(let pass=0;pass<6&&waiting.length&&remaining>0;pass++){const roundBudget=remaining,weighted=waiting.map(m=>{const centerDistance=camera.position.distanceTo(m.group.position),surfaceDistance=Math.max(0,centerDistance-m.radius),weight=1/(1+Math.pow(surfaceDistance,.92));return{m,weight}}),weightSum=weighted.reduce((sum,x)=>sum+x.weight,0);let spent=0;for(const{m,weight}of weighted){const cap=m.points.geometry.attributes.position.count,current=allocation.get(m),share=Math.max(1,Math.floor(roundBudget*weight/weightSum)),give=Math.min(share,cap-current,remaining-spent);if(give>0){allocation.set(m,current+give);spent+=give}}remaining-=spent;waiting=waiting.filter(m=>allocation.get(m)<m.points.geometry.attributes.position.count);if(!spent)break}return allocation}
function visuals(t,dt){const[near]=nearest(),active=models.filter(m=>m?.born&&m.points);if(t-lastBudgetUpdate>.15||budgetTargets.size!==active.length){budgetTargets=distributeBudget(active,near);lastBudgetUpdate=t}const smoothing=1-Math.exp(-dt/1.05);for(const m of models){if(!m)continue;m.group.visible=m.born;if(!m.born||!m.points)continue;const d=camera.position.distanceTo(m.group.position),surfaceDistance=Math.max(0,d-m.radius),u=m.points.material.uniforms,target=budgetTargets.get(m)||300;if(m.drawCurrent===undefined)m.drawCurrent=Math.min(300,target);m.drawCurrent+=(target-m.drawCurrent)*smoothing;const draw=Math.max(1,Math.round(m.drawCurrent));m.points.geometry.setDrawRange(0,draw);u.time.value=t;u.spread.value=diffusionAtSurfaceDistance(surfaceDistance);u.size.value=(surfaceDistance<1.8?8:d<C.far0?10:9)*THREE.MathUtils.clamp(d/7.2,1,C.pointScale);u.alpha.value=(surfaceDistance<1.8?.9:d<C.far0?.76:.62)*(focusedId&&m.id!==focusedId?.18:1);u.highlight.value=m===near||m.id===focusedId?1:0;if(m.visual)m.visual.visible=d<C.far0*1.6&&(!focusedId||m.id===focusedId)}}
function resize(){const w=root.clientWidth,h=root.clientHeight;if(!w||!h)return;if(camera.aspect!==w/h){renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();
  // 竖屏手机横向视角很窄：镜头拉远到能看全外层球壳，粒子按比例放大，扩散阈值跟着走
  const halfH=Math.atan(Math.tan(THREE.MathUtils.degToRad(camera.fov/2))*camera.aspect);C.fit=Math.max(7.2,3.1/Math.tan(halfH));C.pointScale=Math.min(1.9,C.fit/7.2);C.far0=C.fit*.97;C.far1=C.fit*1.7;
  if(!userMoved){camera.position.setLength(C.fit);aimAt(aggregateCenter())}}}
function frame(){requestAnimationFrame(frame);resize();const dt=Math.min(.04,clock.getDelta()),t=performance.now()/1000,now=performance.now();move(dt,now);visuals(t,dt);updateMemoryAtmosphere();memoryStars.rotation.y=t*.0015;axisGlobe.group.position.copy(aggregateCenter());axisGlobe.sphere.rotation.y=t*.055;renderer.render(scene,camera)}
const input=()=>{lastInput=performance.now()};
// 点中心地球 → 回世界线；点物件 → 告诉父页面是哪一件（父页面跳到那天的手帐，或进入打印）
function pickModel(e){const rect=renderer.domElement.getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top,v=new THREE.Vector3(),edge=new THREE.Vector3();let best=null,bestDepth=Infinity;for(const m of models){if(!m?.born||!m.group.visible)continue;v.copy(m.group.position).project(camera);if(v.z>1)continue;const sx=(v.x+1)/2*rect.width,sy=(1-v.y)/2*rect.height;edge.copy(m.group.position).addScaledVector(camera.up,m.radius).project(camera);const r=Math.max(26,Math.abs((1-edge.y)/2*rect.height-sy)*1.1),depth=camera.position.distanceTo(m.group.position);if(Math.hypot(sx-x,sy-y)<=r&&depth<bestDepth){best=m;bestDepth=depth}}return best}
const handleTap=e=>{if(Math.hypot(e.clientX-pointerDownX,e.clientY-pointerDownY)>6)return;const rect=renderer.domElement.getBoundingClientRect(),pointer=new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),raycaster=new THREE.Raycaster();raycaster.setFromCamera(pointer,camera);const hitModel=pickModel(e);if(hitModel&&window.parent!==window){window.parent.postMessage({type:'memory-universe:open',id:hitModel.id},location.origin);return}if(raycaster.intersectObject(axisGlobe.sphere,false).length&&window.parent!==window)window.parent.postMessage({type:'memory-universe:enter-globe'},location.origin)};
// 镜头沿视线前后移动：滚轮和双指缩放共用
function dolly(amount){const f=new THREE.Vector3(-Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),-Math.cos(yaw)*Math.cos(pitch)),before=camera.position.clone();camera.position.copy(collide(before.clone().addScaledVector(f,amount),before,true));userMoved=true;input()}
// 多指：两指捏合缩放；只剩一指时接着拖，不跳
const touches=new Map();let pinchDistance=0,multiTouch=false;const spread=()=>{const[a,b]=[...touches.values()];return Math.hypot(a.x-b.x,a.y-b.y)};
renderer.domElement.onpointerdown=e=>{focusedId=null;touches.set(e.pointerId,{x:e.clientX,y:e.clientY});renderer.domElement.setPointerCapture(e.pointerId);if(touches.size>=2){drag=false;multiTouch=true;pinchDistance=spread()}else{drag=true;multiTouch=false;lastX=pointerDownX=e.clientX;lastY=pointerDownY=e.clientY}input()};
renderer.domElement.onpointermove=e=>{if(!touches.has(e.pointerId))return;touches.set(e.pointerId,{x:e.clientX,y:e.clientY});if(touches.size>=2){const d=spread();dolly((d-pinchDistance)*.018);pinchDistance=d;return}if(!drag)return;orbitAroundCenter(e.clientX-lastX,e.clientY-lastY);userMoved=true;lastX=e.clientX;lastY=e.clientY;input()};
const release=e=>{touches.delete(e.pointerId);if(touches.size===1){const[p]=[...touches.values()];lastX=p.x;lastY=p.y;drag=true;return}if(touches.size===0){const wasDrag=drag;drag=false;if(wasDrag&&!multiTouch&&e.type==='pointerup')handleTap(e)}};
renderer.domElement.onpointerup=release;renderer.domElement.onpointercancel=release;renderer.domElement.onwheel=e=>{e.preventDefault();dolly(e.deltaY*.0025)};
addEventListener('keydown',e=>{if(e.target.closest('input,select,textarea,dialog'))return;keys.add(e.key.toLowerCase());input()});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
ui.back.onclick=()=>{const[m]=nearest();if(m){camera.position.copy(m.group.position.clone().add(new THREE.Vector3(0,.2,m.radius+1.2)));aimAt(m.group.position)}lastInput=performance.now();ui.back.hidden=true};
// Append newly completed backend assets; existing model indices remain stable.
const loadedIds=new Set();
let syncing=false,queuedFiles=null;
// 从手帐跳过来看某一件：镜头飞到它外侧，停 9 秒再恢复自动环绕
// 从侧面看（切向 + 略向外），背景是太空而不是挤在中心的其他记忆；其余物件在用户碰屏幕前先调暗
function focusModel(id){const m=models.find(x=>x?.id===id);if(!m){pendingFocus=id;return}pendingFocus=null;focusedId=id;const target=m.group.position.clone(),out=target.lengthSq()>1e-4?target.clone().normalize():new THREE.Vector3(0,0,1),side=new THREE.Vector3().crossVectors(new THREE.Vector3(0,1,0),out);if(side.lengthSq()<1e-4)side.set(1,0,0);side.normalize();camera.position.copy(target.clone().addScaledVector(side.multiplyScalar(.8).add(out.multiplyScalar(.6)).normalize(),m.radius+2.4).add(new THREE.Vector3(0,.3,0)));aimAt(target);userMoved=true;lastInput=performance.now()+9000}
async function syncModels(files){
  if(syncing){queuedFiles=files;return}
  syncing=true;
  try{
    layoutPositions=getStableLayout(files);
    // 要聚焦的那件先载入，其余按时间顺序
    const pending=files.filter(f=>!loadedIds.has(f.id)).sort((a,b)=>(b.id===pendingFocus)-(a.id===pendingFocus));
    if(!files.length){ui.loading.textContent='你的记忆宇宙，正等待第一张照片';return}
    if(pending.length)ui.loading.classList.remove('is-hidden');
    for(const f of pending){
      const index=files.findIndex(item=>item.id===f.id);
      ui.loading.textContent=`正在让「${f.name}」成为星点…`;
      try{
        const asset=await load(f.url);
        models[index]=prepare(asset.gltf,f.name,index,asset.palette);models[index].id=f.id;
        loadedIds.add(f.id);particles();buildLine();memoryAtmosphere.refreshToken++;
        ui.loading.textContent=`${loadedIds.size} 件记忆已进入宇宙`;
        window.dispatchEvent(new CustomEvent('memory-universe:model-loaded',{detail:{id:f.id,count:loadedIds.size}}));
        if(pendingFocus===f.id)focusModel(f.id);
        if(embedded)window.parent.postMessage({type:'memory-universe:loaded',count:loadedIds.size,total:files.length},location.origin);
      }catch(e){ui.loading.textContent=`「${f.name}」载入失败，稍后自动重试`;console.error('记忆载入失败',e)}
      await new Promise(resolve=>setTimeout(resolve,80));
    }
    if(loadedIds.size===files.length)setTimeout(()=>ui.loading.classList.add('is-hidden'),1800);
  }finally{syncing=false;if(queuedFiles){const next=queuedFiles;queuedFiles=null;syncModels(next)}}
}
async function startLocalPreview(){
  document.querySelector('#add-memory').hidden=true;
  document.querySelector('.memory-progress').hidden=true;
  try{
    const html=await(await fetch('./models-source/')).text(),doc=new DOMParser().parseFromString(html,'text/html');
    const files=[...doc.querySelectorAll('a')].map(a=>decodeURIComponent(a.getAttribute('href')||'')).filter(x=>/\.glb$/i.test(x)).map((x,index)=>({id:`local-${index}-${x}`,name:x.split('/').pop().replace(/\.glb$/i,''),url:`./models-source/${x}`}));
    await syncModels(files);
  }catch(e){ui.loading.textContent=`无法读取本地记忆模型：${e.message}`;console.error(e)}
}
// 嵌在遇见集 /universe 里：节点由父页面给（和手帐同一份数据），点物件交回父页面处理；不连建模后端
function startEmbedded(){
  document.querySelector('.hint').textContent='拖动旋转 · 双指缩放 · 点物件回到那天';
  addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==window.parent)return;const data=e.data;if(data?.type==='memory-universe:nodes'&&Array.isArray(data.nodes))syncModels(data.nodes.filter(n=>typeof n?.id==='string'&&typeof n.url==='string'&&(n.url.startsWith('/')||n.url.startsWith(`blob:${location.origin}/`))));if(data?.type==='memory-universe:focus'&&typeof data.id==='string')focusModel(data.id)});
  window.parent.postMessage({type:'memory-universe:ready'},location.origin);
}
if(embedded)startEmbedded();else if(location.port==='4173')startLocalPreview();else startMemoryClient(syncModels);frame();
