// 示例手帐（首页「看看别人的遇见集」/「我的 · 示例内容」载入）。
//
// 两类场景，都按「一天一条路线」组织：
// - 旅行：英国 5 天，伦敦 → 七姐妹白崖 → 牛津 → 惠特比 → 爱丁堡，自南往北。
// - 日常：深圳两个周六，洪湖/仙湖一线，深圳湾/蛇口一线。
//
// 每个点 = 一张照片 + 当时说的一句话 + 手帐里的一段。时间是当地时钟（HH:MM），
// 载入时按设备时区换算，手帐上显示的就是这个钟点。
// 照片主体尽量选轮廓简单的动物、植物、单个物件：后面要走 Tripo 图生 3D，主体越干净，模型越好看。
// 队员实拍在 /demo/uk-*.jpg 和 /seed/（白崖、灯塔、惠特比海鸥）；其余来自 Wikimedia Commons 的开放授权图片，出处见 public/demo/CREDITS.md。
import type { Category, Luck } from "../types";
import type { DropCategory, KeepCategory } from "../memo/types";

export interface DemoStop {
  id: string;
  /** 小遇为什么把这段留下（手帐里「为什么留下」） */
  agentCategory: KeepCategory;
  why: string;
  time: string;
  name: string;
  category: Category;
  photo: string;
  /** 「国家 · 城市 · 具体地点」，手帐和地图上显示最后一段 */
  place: string;
  country: string;
  lat: number;
  lng: number;
  /** 当时说的原话（手帐金句 / 看原话） */
  quote: string;
  /** 手帐里这一段 */
  text: string;
  cognition: string;
  fun: string;
  luck: Luck;
  question: string;
  memorySentence: string;
}

/** 没写进手帐的片段：折叠（留着但不写）或丢掉——让人看到小遇确实在筛，不是有啥写啥 */
export interface DemoAside {
  id: string;
  time: string;
  decision: "fold" | "drop";
  category: KeepCategory | DropCategory;
  trigger: string;
  why: string;
  /** 我说的原话；别人说的就放 others */
  quote?: string;
  others?: string;
}

export interface DemoDay {
  dayKey: string;
  title: string;
  stops: DemoStop[];
  asides?: DemoAside[];
}

/** 改示例内容就改这个版本号：已经载入旧示例的设备会自动换成新的 */
export const DEMO_VERSION = "2026-09-24-agent-2";

const low = (text: string, basis: string): Luck => ({ text, basis, confidence: "low" });

export const DEMO_DAYS: DemoDay[] = [
  {
    dayKey: "2026-07-11",
    title: "清晨的荷花，和一朵像拖鞋的兰花",
    stops: [
      {
        id: "demo-sz-lotus",
        agentCategory: "observation",
        why: "你盯着荷花一瓣瓣打开，记下了「里面还攥着」",
        time: "07:40",
        name: "清晨的荷花",
        category: "plant",
        photo: "/demo/shenzhen-lotus.jpg",
        place: "中国 · 深圳 · 洪湖公园",
        country: "CHN",
        lat: 22.5657,
        lng: 114.121,
        quote: "早上七点多来的，荷花正一瓣一瓣地打开，外面几瓣已经摊开了，里面还攥着。",
        text: "周六起了个大早去洪湖公园。七点多的荷花池刚醒，一朵荷花正在打开，外面几瓣已经摊平，里面几瓣还攥着，叶子上的露水在滚。在深圳住了这么多年，这是我第一次赶在清晨看荷花开。",
        cognition: "莲（荷花，Nelumbo nucifera），夏季开花，花朵清晨开放、午后闭合，一朵花能开三四天。",
        fun: "荷叶表面布满纳米级的蜡质突起，水珠落上去会滚走，顺便带走灰尘，这叫「荷叶效应」。",
        luck: low("赶上花开的那一刻，适合开始一件新的事。", "荷花多在清晨开放"),
        question: "你更喜欢它全开的样子，还是正在打开的样子？",
        memorySentence: "荷花是一瓣一瓣醒过来的。",
      },
      {
        id: "demo-sz-orchid",
        agentCategory: "retold_fact",
        why: "你把听来的新知说成了自己的话：虫子从后门钻出来带走花粉",
        time: "10:50",
        name: "硬叶兜兰",
        category: "plant",
        photo: "/demo/shenzhen-orchid.jpg",
        place: "中国 · 深圳 · 仙湖植物园",
        country: "CHN",
        lat: 22.5795,
        lng: 114.179,
        quote: "这朵兰花长了一个小口袋，像一只拖鞋。说是虫子掉进去，得从后门钻出来，顺便把花粉带走。",
        text: "从洪湖打车去仙湖植物园，在兰花温室里第一次见到兜兰。它的唇瓣鼓成一个粉色的小口袋，真的像一只拖鞋。旁边的牌子写着：虫子滑进口袋以后，只能从后面一条窄路爬出来，出来的时候身上就粘满了花粉。一朵花，给虫子设计了一条单行道。",
        cognition: "硬叶兜兰（Paphiopedilum micranthum），唇瓣呈囊状，产于云南、贵州、广西，属国家重点保护野生植物。",
        fun: "兜兰的「口袋」其实是个陷阱：昆虫滑进去后只能从固定出口爬出，顺路完成授粉。",
        luck: low("遇见单行道的花，今天做决定不用回头。", "兜兰的授粉通道只有一个出口"),
        question: "如果你是那只虫子，会不会觉得被设计了？",
        memorySentence: "一朵花，给虫子设计了一条单行道。",
      },
      {
        id: "demo-sz-nepenthes",
        agentCategory: "difference",
        why: "亲眼确认「它真的在吃肉」，认知被刷新",
        time: "14:30",
        name: "猪笼草",
        category: "plant",
        photo: "/demo/shenzhen-nepenthes.jpg",
        place: "中国 · 深圳 · 珍稀植物区",
        country: "CHN",
        lat: 22.578,
        lng: 114.1832,
        quote: "猪笼草的笼子里真有水，还有淹死的小虫子。它是真的在吃肉。",
        text: "下午在珍稀植物区看到猪笼草。一个个挂着的小笼子，上面还带着盖子。凑近看，笼子里真的有半笼水，泡着几只小虫。原来植物也会吃肉，只是吃得很安静。",
        cognition: "猪笼草（Nepenthes），叶片末端特化成捕虫笼，笼内的消化液可以分解落入的昆虫。",
        fun: "猪笼草的笼盖主要用来挡雨，防止消化液被雨水冲淡，并不会「啪」地一下盖上。",
        luck: low("安静的猎手，提醒你今天少说多看。", "猪笼草靠气味和蜜腺吸引昆虫，全程不动"),
        question: "你觉得它算植物，还是算动物？",
        memorySentence: "植物也会吃肉，只是吃得很安静。",
      },
    ],
  },
  {
    dayKey: "2026-07-18",
    title: "退潮后的深圳湾，和朋友家会眨眼的守宫",
    stops: [
      {
        id: "demo-sz-fiddler-crab",
        agentCategory: "observation",
        why: "你给招潮蟹配了表情：「像在跟人打招呼」",
        time: "09:10",
        name: "招潮蟹",
        category: "animal",
        photo: "/demo/shenzhen-fiddler-crab.jpg",
        place: "中国 · 深圳 · 深圳湾公园红树林",
        country: "CHN",
        lat: 22.52,
        lng: 113.978,
        quote: "退潮以后滩涂上全是小螃蟹，一只大钳子一只小钳子，举着大钳子一直挥，像在跟人打招呼。",
        text: "趁早上退潮去深圳湾。栈道下的滩涂上爬满了小螃蟹，每只都是一只钳子大、一只钳子小，举着那只大钳子不停地挥。我在栏杆边蹲了二十分钟，它们一有动静就钻回洞里，过一会儿又探出来接着挥。",
        cognition: "招潮蟹，雄蟹有一只特别大的螯，退潮时在滩涂上挥动，用来求偶和宣示领地。",
        fun: "每只招潮蟹挥螯的节奏都不太一样，雌蟹会按挥舞的速度和力度挑选配偶。",
        luck: low("被一群螃蟹招手，今天适合主动打招呼。", "招潮蟹只在退潮时出洞挥螯"),
        question: "如果它们是在跟你打招呼，你会怎么回？",
        memorySentence: "滩涂上，一群螃蟹举着大钳子跟我打招呼。",
      },
      {
        id: "demo-sz-mimosa",
        agentCategory: "first_experience",
        why: "第一次亲手碰含羞草，还给了它性格：「会害羞」",
        time: "11:20",
        name: "含羞草",
        category: "plant",
        photo: "/demo/shenzhen-mimosa.jpg",
        place: "中国 · 深圳 · 深圳湾公园草坡",
        country: "CHN",
        lat: 22.518,
        lng: 113.959,
        quote: "我碰了一下，它的叶子一片一片合起来了，好像真的会害羞。",
        text: "往回走的时候，路边草坡上有一片细细的羽毛状叶子。朋友说这是含羞草，让我碰一下。手指刚碰上，叶子就一对一对地合起来，整根叶柄都垂了下去，过了好几分钟才慢慢张开。小时候只在课本里见过，今天第一次亲手碰到。",
        cognition: "含羞草（Mimosa pudica），叶片受到触碰后会迅速闭合下垂，属于植物的感震运动。",
        fun: "叶子合起来靠的是叶枕细胞快速失水，重新张开大概要十几分钟。",
        luck: low("碰一下就有回应，今天的小尝试都会有反馈。", "含羞草对触碰的反应在一秒内发生"),
        question: "你小时候是不是也把一整片含羞草都碰过一遍？",
        memorySentence: "课本里的含羞草，今天第一次亲手碰到。",
      },
      {
        id: "demo-sz-leopard-gecko",
        agentCategory: "retold_fact",
        why: "朋友讲的新知被你复述了：会眨眼，爬不上玻璃",
        time: "19:30",
        name: "豹纹守宫",
        category: "animal",
        photo: "/demo/shenzhen-leopard-gecko.jpg",
        place: "中国 · 深圳 · 蛇口朋友家",
        country: "CHN",
        lat: 22.493,
        lng: 113.916,
        quote: "它的眼睛会眨！朋友说它是守宫里少有长眼皮的，而且脚上没有吸盘，爬不上玻璃。",
        text: "晚上去蛇口朋友家吃饭，认识了他新养的豹纹守宫。橙黄色的身体上全是黑点，尾巴胖胖的，朋友说那是它存脂肪的地方。最让我意外的是它会眨眼——大多数壁虎没有眼皮，它有。它趴在石头上慢慢眨了一下，像在认真打量我。",
        cognition: "豹纹守宫（Eublepharis macularius），原产南亚干旱地区，有可活动的眼睑，脚趾没有吸盘，尾巴用来储存脂肪。",
        fun: "豹纹守宫遇到危险会主动断尾，断下来的尾巴还会扭动一会儿，引开敌人的注意。",
        luck: low("被一只会眨眼的守宫认真打量，今天的你很值得被记住。", "守宫眨眼通常表示它处在放松状态"),
        question: "你第一次见它，是先注意到斑点，还是那双眼睛？",
        memorySentence: "它会眨眼，是守宫里的少数派。",
      },
    ],
    asides: [
      { id: "demo-aside-bay-roots", time: "10:05", decision: "fold", category: "observation", trigger: "红树林的根", why: "带感受的观察，但和招潮蟹在同一处，先折叠", quote: "红树林的根都露在外面，像一把把插在泥里的叉子。" },
      { id: "demo-aside-bay-sun", time: "12:30", decision: "drop", category: "complaint", trigger: "太晒", why: "抱怨天气，不是新鲜体验", quote: "太晒了，防晒霜又忘带了。" },
      { id: "demo-aside-bay-metro", time: "18:40", decision: "drop", category: "functional", trigger: "问地铁出口", why: "问路，只是事务", quote: "地铁坐到蛇口港站，是 C 出口对吧？" },
    ],
  },
  {
    dayKey: "2026-09-12",
    title: "伦敦：公园里的鹈鹕，和夜里的狐狸",
    stops: [
      {
        id: "demo-uk-big-ben",
        agentCategory: "difference",
        why: "「原来是钟不是塔」，一次常识被纠正",
        time: "10:05",
        name: "大本钟",
        category: "landscape",
        photo: "/demo/uk-big-ben.jpg",
        place: "英国 · 伦敦 · 威斯敏斯特",
        country: "GBR",
        lat: 51.5007,
        lng: -0.1246,
        quote: "原来大本钟是那口钟的名字，不是这座塔。红色双层巴士从旁边开过去的时候，我才真觉得到伦敦了。",
        text: "早上十点从威斯敏斯特桥走过来，大本钟就立在街角。之前一直以为「大本钟」说的是整座塔，查了才知道它只是塔里那口钟的名字，塔叫伊丽莎白塔。红色双层巴士一辆接一辆开过去，这一刻才真觉得：到伦敦了。",
        cognition: "伊丽莎白塔是英国议会大厦的钟楼，「大本钟」原本指塔内那口大钟。",
        fun: "钟楼原名就叫「钟楼」，2012 年为纪念女王登基 60 周年才改名为伊丽莎白塔。",
        luck: low("第一天就站在整点的钟下面，这趟行程会很准时。", "到达时间正好在整点附近"),
        question: "你第一次见它，是先听见钟声，还是先看见塔？",
        memorySentence: "大本钟是钟的名字，不是塔的。",
      },
      {
        id: "demo-uk-pelican",
        agentCategory: "first_experience",
        why: "城市公园里撞见鹈鹕，你拿自己的胳膊比它的嘴",
        time: "11:40",
        name: "圣詹姆斯公园的鹈鹕",
        category: "animal",
        photo: "/demo/london-pelican.jpg",
        place: "英国 · 伦敦 · 圣詹姆斯公园",
        country: "GBR",
        lat: 51.5027,
        lng: -0.134,
        quote: "公园里居然有鹈鹕！它就站在石头上，离我不到两米，嘴比我整条胳膊还长。",
        text: "从议会广场往西走几分钟就是圣詹姆斯公园。湖边的石头上站着一只鹈鹕，离我不到两米，嘴巴长得不讲道理。旁边的大爷说，它们的祖先是 1664 年俄国大使送给国王的礼物，从那以后这片湖就一直有鹈鹕。在市中心的公园里看见这么大的鸟，是今天第一个没想到。",
        cognition: "白鹈鹕。圣詹姆斯公园自 1664 年起饲养鹈鹕，最早是俄国大使送给查理二世的礼物。",
        fun: "鹈鹕的喉囊能装下十几升水，捞到鱼以后要先把水挤掉才能吞下去。",
        luck: low("鹈鹕肯停在你面前，这趟旅行的好奇心会被回应。", "公园里的鹈鹕习惯人群，但很少主动靠近"),
        question: "如果它是 360 年前那份礼物的后代，你想替它问问什么？",
        memorySentence: "市中心的湖边，站着一份 360 年前的礼物的后代。",
      },
      {
        id: "demo-uk-fox",
        agentCategory: "difference",
        why: "你在问「伦敦的狐狸跟流浪猫一样多吗」，是对差异的好奇",
        time: "21:40",
        name: "城市里的狐狸",
        category: "animal",
        photo: "/demo/london-fox.jpg",
        place: "英国 · 伦敦 · 海格特",
        country: "GBR",
        lat: 51.571,
        lng: -0.147,
        quote: "刚才花园里窜出来一只狐狸，就坐在那儿看我，一点都不怕人。伦敦的狐狸跟流浪猫一样多吗？",
        text: "晚上回海格特的住处，路边人家的花园里窜出来一只狐狸。它没跑，坐在草地上盯着我看了好一会儿。后来才知道伦敦城里住着上万只狐狸，夜里翻垃圾桶是常事。可对我来说，这是第一次和一只野生的狐狸对视。",
        cognition: "赤狐。伦敦等英国城市生活着大量城市狐狸，多在夜间出来觅食。",
        fun: "赤狐的尾巴尖通常是白色的，像随身带着一盏小灯。",
        luck: low("夜里和狐狸对视，今晚会睡得很踏实。", "它愿意停下来看你，说明没把你当成威胁"),
        question: "它盯着你看的那几秒，你在想什么？",
        memorySentence: "第一次和一只野生狐狸对视，在伦敦的住宅区。",
      },
    ],
  },
  {
    dayKey: "2026-09-13",
    title: "白崖：从海岸警卫小屋走到比奇角灯塔",
    stops: [
      {
        id: "demo-uk-seven-sisters",
        agentCategory: "observation",
        why: "你给白崖找了个比喻：「一排巨大的粉笔」",
        time: "10:20",
        name: "七姐妹白崖",
        category: "landscape",
        photo: "/seed/white-cliff.jpg",
        place: "英国 · 七姐妹白崖 · 西福德角",
        country: "GBR",
        lat: 50.7641,
        lng: 0.1466,
        quote: "天阴得很重，可是崖壁白得发亮，像有人在海边摆了一排巨大的粉笔。",
        text: "从西福德角的小路往下走，海岸警卫小屋后面就是七姐妹白崖。天阴得很重，崖壁却白得发亮，一层一层排到海的尽头，像有人在海边竖了一排巨大的粉笔。风很大，帽子差点被吹走。",
        cognition: "七姐妹白崖是英吉利海峡边的白垩海崖，由远古海洋微生物的钙质外壳沉积而成。",
        fun: "白崖每年会被海浪侵蚀掉几十厘米，崖边的海岸警卫小屋总有一天要面对大海。",
        luck: low("阴天里的白崖最白，今天适合看清一件事。", "云层压低时崖壁和天空的反差最大"),
        question: "你第一眼觉得它像什么？",
        memorySentence: "七姐妹白崖，白得像海边的一排粉笔。",
      },
      {
        id: "demo-uk-red-box",
        agentCategory: "observation",
        why: "你看出了画面感：「好像专门摆好等人来拍」",
        time: "12:50",
        name: "草坡上的红箱子",
        category: "artifact",
        photo: "/demo/uk-red-box.jpg",
        place: "英国 · 七姐妹白崖 · 伯灵峡",
        country: "GBR",
        lat: 50.7432,
        lng: 0.2012,
        quote: "整片草坡上什么都没有，就一个红箱子和一棵被风吹歪的树，好像专门摆好等人来拍。",
        text: "沿着崖顶往东走，上上下下翻过几座「姐妹」。伯灵峡上方的草坡上什么都没有，只有一个红色的箱子，和远处一棵被海风吹歪的小树。绿、红、灰三种颜色，干净得像一张明信片。",
        cognition: "停在南唐斯丘陵草坡上的一只红色大型集装箱，远处是被海风常年吹弯的小树。",
        fun: "英格兰南部常年刮西南风，海边丘陵上的树大多朝东北方向倾斜生长。",
        luck: low("在空旷的地方看见一抹红，今天的运气会很醒目。", "红色在大片绿色背景里最先被看见"),
        question: "如果这个箱子里装着一样东西，你希望是什么？",
        memorySentence: "空荡荡的草坡上，只有一个红箱子。",
      },
      {
        id: "demo-uk-lighthouse",
        agentCategory: "first_experience",
        why: "第一次从崖顶俯看灯塔，连「趴在草上」都记下了",
        time: "15:40",
        name: "比奇角灯塔",
        category: "artifact",
        photo: "/seed/beach-lighthouse.jpg",
        place: "英国 · 七姐妹白崖 · 比奇角",
        country: "GBR",
        lat: 50.7362,
        lng: 0.2432,
        quote: "从崖顶往下看，灯塔在海里，红白两截，小得像玩具。风大到我得趴在草上才敢往下看。",
        text: "走了五个多小时，终于到比奇角。趴在崖顶的草地上往下看，红白相间的灯塔站在海里，小得像一个玩具。它从 1902 年起就一直在这里，替过往的船看着这片悬崖。这是今天路线的终点，也是我第一次从上往下看一座灯塔。",
        cognition: "比奇角灯塔，1902 年建成，立在白垩崖下的海中，红白条纹是它的标志。",
        fun: "比奇角是英国最高的白垩海崖，崖顶离海面约 160 米。",
        luck: low("从高处看见灯塔，接下来的路会有人替你照着。", "灯塔白天也是船只辨认方位的航标"),
        question: "你更想站在灯塔上看崖，还是站在崖上看灯塔？",
        memorySentence: "第一次从上往下看一座灯塔，它小得像玩具。",
      },
    ],
    asides: [
      { id: "demo-aside-cliffs-train", time: "09:30", decision: "drop", category: "functional", trigger: "查车次", why: "问车次和换乘，只是事务", quote: "去西福德的火车是几点来着，路上还要换一次车吗？" },
      { id: "demo-aside-cliffs-sheep", time: "11:40", decision: "fold", category: "observation", trigger: "崖边吃草的羊", why: "有感受，但这一天白崖和灯塔更重要，先折叠", quote: "这边的羊好多，都在崖边上吃草，也不怕掉下去。" },
      { id: "demo-aside-cliffs-sandwich", time: "13:30", decision: "drop", category: "complaint", trigger: "三明治太贵", why: "抱怨价格，不是新鲜体验", quote: "伯灵峡这个三明治要七英镑，太贵了。" },
      { id: "demo-aside-cliffs-call", time: "14:20", decision: "drop", category: "others_only", trigger: "同伴打电话", why: "只有同伴在说话，而且是工作的事", others: "同伴在电话里安排下周的会议" },
      { id: "demo-aside-cliffs-bus", time: "16:30", decision: "drop", category: "functional", trigger: "找公交站", why: "问路，只是事务", quote: "回伊斯特本的公交站在哪边？" },
    ],
  },
  {
    dayKey: "2026-09-14",
    title: "牛津：雨里的阅览室，和学院里的鹿",
    stops: [
      {
        id: "demo-uk-radcliffe",
        agentCategory: "difference",
        why: "以为是教堂，其实是阅览室，你在雨里看了很久",
        time: "10:30",
        name: "拉德克利夫图书馆",
        category: "landscape",
        photo: "/demo/uk-radcliffe-camera.jpg",
        place: "英国 · 牛津 · 拉德克利夫广场",
        country: "GBR",
        lat: 51.7534,
        lng: -1.254,
        quote: "我一直以为这是个教堂，结果是图书馆的阅览室。下着雨，撑伞站在外面看了很久。",
        text: "雨从早上一直下。拉德克利夫广场上那座圆顶建筑，我一直以为是教堂，走近才知道是博德利图书馆的阅览室，只对持证的人开放。撑着伞在外面站了很久，看雨水顺着石墙往下流。",
        cognition: "拉德克利夫图书馆（Radcliffe Camera），1749 年建成，是牛津大学博德利图书馆的阅览室。",
        fun: "「Camera」在拉丁语里是「房间」的意思，它的名字直译过来就是「拉德克利夫的房间」。",
        luck: low("雨天遇到图书馆，适合把一个问题想透。", "雨天的广场人最少"),
        question: "如果能进去坐一下午，你会带哪本书？",
        memorySentence: "以为是教堂，其实是一间圆形的阅览室。",
      },
      {
        id: "demo-uk-fallow-deer",
        agentCategory: "observation",
        why: "「来参观学校，结果看了半天鹿」，你被意外吸引住了",
        time: "13:40",
        name: "莫德林学院的黇鹿",
        category: "animal",
        photo: "/demo/oxford-deer.jpg",
        place: "英国 · 牛津 · 莫德林学院鹿苑",
        country: "GBR",
        lat: 51.7522,
        lng: -1.2447,
        quote: "学院里面养着一群鹿，就在草地上吃草。我是来参观学校的，结果看了半天鹿。",
        text: "雨停了，去莫德林学院。穿过回廊，草地上竟然有一群鹿在吃草，身上带着白色的斑点，公鹿的角像两只摊开的手掌。学院从 18 世纪就开始养鹿了。本来是来看学校的，结果我在栅栏外看了半个小时的鹿。",
        cognition: "黇鹿（扇角鹿）。牛津大学莫德林学院的鹿苑自 18 世纪起饲养一群黇鹿。",
        fun: "黇鹿的角是扁平的掌状，每年春天脱落，再重新长出来。",
        luck: low("在书院里遇见鹿，今天适合慢下来。", "鹿群在人少的午后更愿意靠近栅栏"),
        question: "一所养鹿的大学，你想在这里读什么？",
        memorySentence: "一所大学里养着一群鹿，这件事本身就很牛津。",
      },
      {
        id: "demo-uk-port-meadow",
        agentCategory: "difference",
        why: "「谁也不管谁」，你看出了这里的生活节奏",
        time: "17:20",
        name: "河里喝水的马",
        category: "landscape",
        photo: "/demo/oxford-port-meadow.jpg",
        place: "英国 · 牛津 · 港口草地",
        country: "GBR",
        lat: 51.7686,
        lng: -1.2805,
        quote: "马就站在河里喝水，旁边有人在开帆船，谁也不管谁。",
        text: "傍晚走到城北的港口草地。几匹马站在泰晤士河的浅水里喝水，帆船俱乐部的小船从它们身边滑过去，谁也不理谁。这片草地上千年没被犁过，牛津的市民至今还有权在这里放牧。",
        cognition: "港口草地（Port Meadow）是牛津城北的公共草地，千年来未经耕作，常见散养的马和牛。",
        fun: "港口草地在 1086 年的《末日审判书》里就有记载。",
        luck: low("看见马和帆船各走各的，今天不用迁就谁。", "草地上的马是散养的，行动完全自由"),
        question: "你愿意当那匹马，还是开帆船的人？",
        memorySentence: "马在河里喝水，帆船从旁边滑过去。",
      },
    ],
  },
  {
    dayKey: "2026-09-15",
    title: "惠特比：修道院、菊石，和抢薯条的海鸥",
    stops: [
      {
        id: "demo-uk-whitby-abbey",
        agentCategory: "memory",
        why: "看到废墟想起吸血鬼的故事，留下这份联想",
        time: "09:50",
        name: "惠特比修道院",
        category: "landscape",
        photo: "/demo/whitby-abbey.jpg",
        place: "英国 · 惠特比 · 惠特比修道院",
        country: "GBR",
        lat: 54.4885,
        lng: -0.6076,
        quote: "爬了 199 级台阶上来，修道院只剩下骨架，风从窗洞里穿过去。怪不得吸血鬼的故事要写在这里。",
        text: "早上爬完 199 级台阶，修道院就在崖顶上，只剩石头的骨架，海风从空窗洞里穿过去。《德古拉》的作者当年就是在惠特比度假时攒下了故事的素材。站在废墟里，我第一次明白「哥特」这个词是什么感觉。",
        cognition: "惠特比修道院始建于公元 657 年，现存的是 13 世纪哥特式教堂遗址，也是小说《德古拉》的灵感来源之一。",
        fun: "布拉姆·斯托克 1890 年在惠特比度假时，在当地图书馆里第一次读到「德古拉」这个名字。",
        luck: low("在废墟里站一会儿，今天的烦恼会显得很小。", "遗址已经在崖顶站了七百多年"),
        question: "你觉得废墟比完整的建筑更好看吗？",
        memorySentence: "修道院只剩骨架，风从窗洞里穿过去。",
      },
      {
        id: "demo-uk-ammonite",
        agentCategory: "retold_fact",
        why: "你把「一亿八千万年前它还活着」说成了自己的震撼",
        time: "12:30",
        name: "菊石化石",
        category: "mineral",
        photo: "/demo/whitby-ammonite.jpg",
        place: "英国 · 惠特比 · 惠特比博物馆",
        country: "GBR",
        lat: 54.483,
        lng: -0.619,
        quote: "它是石头，可是一圈一圈的，像还在转。一亿八千万年前它是活的，在海里游。",
        text: "中午躲进潘内特公园里的惠特比博物馆。一整柜的菊石，一圈一圈的螺纹，像还在慢慢转。讲解员说它们大多来自附近海边的崖壁，是一亿八千万年前侏罗纪海里的动物，惠特比的镇徽上就画着三只菊石。我隔着玻璃看了很久。",
        cognition: "普通指菊石（Dactylioceras commune），约 1.8 亿年前侏罗纪早期的海洋软体动物化石，约克郡海岸常见。",
        fun: "当地传说圣希尔达把遍地的蛇变成了石头，所以惠特比人以前会给菊石刻上蛇头出售。",
        luck: low("和一亿八千万年前的东西对视过，今天的急事都不算急。", "菊石是地质年代的「标准化石」"),
        question: "如果一亿年后有人发现你留下的东西，你希望是什么？",
        memorySentence: "一亿八千万年前，它还在海里游。",
      },
      {
        id: "demo-uk-herring-gull",
        agentCategory: "observation",
        why: "你说海鸥「比我还像在看风景」，带着自嘲的观察",
        time: "15:20",
        name: "港口的银鸥",
        category: "animal",
        photo: "/seed/whitby-harbor.jpg",
        place: "英国 · 惠特比 · 惠特比港",
        country: "GBR",
        lat: 54.4857,
        lng: -0.6143,
        quote: "这只海鸥就站在桩子上，一动不动，比我还像在看风景。刚才有人的薯条被抢了。",
        text: "下午回到港口。一只银鸥站在系船桩上，一动不动地看着对岸的红屋顶，比我还像游客。几分钟前，它的同伴刚从一个小孩手里抢走了一根薯条。惠特比的海鸥出了名的大胆，码头上到处贴着「请勿喂食」。",
        cognition: "银鸥（Herring Gull），英国海滨城镇最常见的大型海鸥，以胆大、会抢食出名。",
        fun: "银鸥的喙上有一个红点，雏鸟啄这个红点，父母才会把食物吐出来喂它。",
        luck: low("被海鸥盯上之前先把薯条收好，今天的好运要自己护着。", "港口的银鸥会记住谁手里有吃的"),
        question: "它站在那里，看的是风景还是你的薯条？",
        memorySentence: "它站在桩子上，比我更像在看风景。",
      },
    ],
  },
  {
    dayKey: "2026-09-16",
    title: "爱丁堡：火山上的城堡，和长刘海的牛",
    stops: [
      {
        id: "demo-uk-edinburgh-castle",
        agentCategory: "retold_fact",
        why: "「那块黑石头原来是火山」，你复述了打动你的新知",
        time: "10:10",
        name: "爱丁堡城堡",
        category: "landscape",
        photo: "/demo/uk-edinburgh-castle.jpg",
        place: "英国 · 爱丁堡 · 城堡岩",
        country: "GBR",
        lat: 55.9476,
        lng: -3.203,
        quote: "城堡是长在石头上的，那块黑色的石头原来是火山。",
        text: "从城堡台阶下往上看，城墙和黑色的岩石长在一起，分不清哪里是人砌的。这块城堡岩是三亿多年前一座火山留下的火山颈，爱丁堡就是在火山上长出来的城市。",
        cognition: "爱丁堡城堡建在城堡岩上，城堡岩是约 3.5 亿年前火山活动留下的火山颈。",
        fun: "城堡里的「一点钟大炮」每天下午一点准时鸣放，最早是给港口的船对时用的。",
        luck: low("站在火山上的城市里，今天适合做一件需要底气的事。", "城堡岩已经稳稳站了三亿多年"),
        question: "你会选择住在一座火山上吗？",
        memorySentence: "爱丁堡是长在一座火山上的城市。",
      },
      {
        id: "demo-uk-thistle",
        agentCategory: "first_experience",
        why: "第一次被苏格兰国花扎到，才知道它的名字",
        time: "13:20",
        name: "蓟花",
        category: "plant",
        photo: "/demo/edinburgh-thistle.jpg",
        place: "英国 · 爱丁堡 · 亚瑟王座",
        country: "GBR",
        lat: 55.944,
        lng: -3.162,
        quote: "山坡上全是这种紫色的花，一碰手就被扎了。后来才知道这是苏格兰的国花。",
        text: "中午爬亚瑟王座，半山腰的草坡上开着一丛丛紫色的花，毛茸茸的。我伸手去摸，被扎了一下。下山查了才知道是蓟，苏格兰的国花。传说维京人夜里偷袭，光脚踩到了蓟，痛得叫出声来，苏格兰人才被惊醒。",
        cognition: "蓟，苏格兰的国花，花冠紫色，叶片和花苞布满尖刺。",
        fun: "苏格兰最高级别的骑士勋章叫「蓟花勋章」，格言是「犯我者必受其害」。",
        luck: low("被国花扎一下，算是苏格兰正式跟你打过招呼了。", "蓟的刺是它最有名的地方"),
        question: "一种会扎人的花当国花，你觉得合适吗？",
        memorySentence: "苏格兰的国花，第一次见面就扎了我一下。",
      },
      {
        id: "demo-uk-highland-cow",
        agentCategory: "observation",
        why: "你拿自己的刘海和牛比，这句很像你",
        time: "16:40",
        name: "高地牛",
        category: "animal",
        photo: "/demo/edinburgh-highland-cow.jpg",
        place: "英国 · 爱丁堡 · 彭特兰丘陵",
        country: "GBR",
        lat: 55.887,
        lng: -3.233,
        quote: "它的刘海比我的还长，根本看不见眼睛。站在山坡上，背后就是整座爱丁堡。",
        text: "下午坐公交去城南的彭特兰丘陵，终于见到了高地牛。一头红棕色的牛站在山坡上，刘海长到把眼睛整个盖住，两只角弯得很好看，它身后就是整座爱丁堡和远处的海湾。这是这趟英国行的最后一个下午。",
        cognition: "苏格兰高地牛，长毛、长角的古老牛种，双层被毛让它能在高地的寒风里过冬。",
        fun: "苏格兰人叫它「hairy coo」，一群高地牛不叫 herd，而叫 fold。",
        luck: low("最后一天见到最想见的，这趟旅行算是圆满收尾。", "高地牛性情温和，常在山坡上慢慢吃草"),
        question: "它的刘海底下，是在看你还是在打盹？",
        memorySentence: "它的刘海比我的还长。",
      },
    ],
  },
];

/** 地点的最后一段（「英国 · 七姐妹白崖 · 比奇角」→「比奇角」） */
export function placeTail(place: string): string {
  const parts = place.split(/\s*[·・]\s*/).filter(Boolean);
  return parts.at(-1) ?? place;
}
